server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker
    static_configs:
      - targets:
          - localhost
        labels:
          job: docker
          __path__: /var/lib/docker/containers/*/*.log
          container_name: "{{ .ContainerName }}"
          service: "{{ .ContainerName }}"  # Assuming container name represents the service
          environment: "production"  # You can set this dynamically if needed
          container_id: "{{ .ContainerID }}"
          image: "{{ .ImageName }}"