server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker
    static_configs:
      - targets:
          - localhost
        labels:
          job: docker
          environment: "production"
          __path__: /var/lib/docker/containers/*/*.log

    pipeline_stages:
      - regex:
          expression: '/var/lib/docker/containers/(?P<container_id>[a-f0-9]{64})/(?P<filename>[a-f0-9]{64}-json\.log)'
      - docker:
          container_id: container_id
      - labels:
          container_id:
          container_name: container_name
          image:
